[pytest]
markers =
    smoke: основные проверки работоспособности
    regression: полная проверка функционала
    ui: тесты интерфейса
    buttons: тест кнопок
    inputs: тест инпутов

addopts = 
    --alluredir=allure-results 
    --clean-alluredir 