[pytest]
markers =
    smoke: основные проверки работоспособности
    regression: полная проверка функционала
    ui: тесты интерфейса
    like_button: тест кнопок button
    simple: тест простых кнопок

addopts = 
    --alluredir=allure-results 
    --clean-alluredir 