# .github/workflows/tests.yml
name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run tests
        env:
          SIMPLE_URL: ${{ secrets.SIMPLE_URL }}
          LIKE_BUTTON_URL: ${{ secrets.LIKE_BUTTON_URL }}
          DISABLED_URL: ${{ secrets.DISABLED_URL }}
          SMP_INPUT_URL: ${{ secrets.SMP_INPUT_URL }}
        run: pytest 